# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm ci
      working-directory: ./vista
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm test --if-present
    
    - name: Zip artifact para despliegue
      run: zip proyecto-ucadied.zip ./* -r -T -x vista/public vista/node_modules vista/src vista/*.json vista/*.md

    - name: Subir artifact para trabajo de despliegue
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: proyecto-ucadied.zip
        


  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: 'Esperar por SSH'
      run: |
        while ! nc -w5 -z ${{ secrets.INSTANCE_IP }} 22; do
                sleep 5
                echo "SSH not available..."
        done; echo "SSH ready!"
    - name: 'Detener App'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: opc
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          pid=`lsof -i tcp:8080 | tail -n +2 | awk '{print $2}'`
          if [ "$pid" == "" ]; then
            echo "Process not found"
          else
            kill -9 $pid
          fi
          sudo mkdir -p /app
    - name: 'Descargar artifact del build'
      uses: actions/download-artifact@v2
      with:
        name: node-app


    - name: 'Enviar zip'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: opc
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        port: 22
        source: "proyecto-ucadied.zip"
        target: "proyecto-ucadied"
        strip_components: 0

    - name: 'Correr App'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: opc
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo mkdir -p /var/node/proyecto-ucadied
          cd /var/node/proyecto-ucadied 
          sudo unzip ~/proyecto-ucadied/proyecto-ucadied.zip -o
          sudo chmod a+x app.js
          sudo systemctl restart myapp
